### ISSUE TITLE
LearnFairNB/data/compas_binerized.csv does not exist

### ISSUE THREAD

**Issue by CarlaTeo** [UCLA-StarAI/LearnFairNB#1]
Hi, 

I followed the README but an error occurred when running ./setup.sh:
```
Traceback (most recent call last):
  File "../fairNB/fair_learn.py", line 158, in <module>
    run(args)
  File "../fairNB/fair_learn.py", line 121, in run
    root_params, leaf_params, target_value, target_name, sensitive_var_ids, feature_names, bn_dict, params_dict, df  = initialize(db_file, info_file)
  File "../fairNB/fair_learn.py", line 16, in initialize
    root_params, leaf_params, target_value, target_name, sensitive_var_ids, feature_names, bn_dict, params_dict, df = init_learning(db_file,info_file)
  File "/home/carla/LearnFairNB/fairNB/parameter_learner/data_processor.py", line 136, in init_learning
    df = pd.read_csv(db_file)
  File "/home/carla/miniconda3/envs/gpkit-env/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/carla/miniconda3/envs/gpkit-env/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/carla/miniconda3/envs/gpkit-env/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/carla/miniconda3/envs/gpkit-env/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/carla/miniconda3/envs/gpkit-env/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File /home/carla/LearnFairNB/data/compas_binerized.csv does not exist: '/home/carla/LearnFairNB/data/compas_binerized.csv'
```

**Comment by fritzbayer** [comment]
Indeed, I have the same problem.
